name: 'Deploy to AWS S3'
description: 'Deply to S3'
inputs:
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    description: 'The region of the bucket'
    required: false
    default: 'ap-southeast-1'
  dist-folder:
    description: 'The folder of deployable files'
    required: true
outputs:
  website-url:
    description: 'THe URL of the deployed website.'
runs:
  using: 'docker'
  image: 'Dockerfile'
